version: "3.0"
services:
  db:
    image: mysql:5.7
    volumes:
      - "./vol_mysql:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
   
  web:
    volumes:
      - "./html_wordpress:/var/www/html"
    depends_on:
      - db
    image: wordpress
    links:
      - db
    ports:
      - "8080:80"
    restart: always
