apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-mysql
  labels:
    app: mysql-deployment
spec:
  serviceName: db
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
        - name: container-mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "wordpress"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - name: vol-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: vol-mysql
          persistentVolumeClaim:
            claimName: grant-mysql